version: '3.8'

services:
    api_server:
        build: .
        ports:
            - "4000:3000"
        environment:
            NODE_ENV: production
        depends_on:
            - mysql
        command: npm start

    mysql:
        image: mysql:5.7
        container_name: api-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: music_db
            MYSQL_USER: api
            MYSQL_PASSWORD: api_pass_2312
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password

volumes:
    mysql_data:
        driver: local
