version: '3.8'

services:
    api_server:
        build: .
        ports:
            - "4000:3000"
        environment:
            NODE_ENV: production
        depends_on:
            - mysql
        command: npm start

    mysql:
        image: mysql:8.0
        container_name: api-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: music_db
            MYSQL_USER: api
            MYSQL_PASSWORD: api_pass_2312
        ports: []
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
        driver: local

