services:
  api_server:
    build: .
    ports:
      - "4000:3000"
    environment:
      NODE_ENV: production
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: music_db
      MYSQL_USER: api
      MYSQL_PASSWORD: api_pass_2312
    volumes:
      - mysql_data:/var/lib/mysql 

volumes:
  mysql_data:
    driver: local
